### ISSUE TITLE
REM

### ISSUE THREAD

**Issue by jantimon** [bareynol/mui-theme-creator#7]
Hey 👋 

Really cool idea editor!

Just one question - why would you use REM in 2020 for font sizes?

**Comment by bareynol** [comment]
Hey, and thanks!

Short answer: Material-UI's `Theme` uses `rem` units by default for typography font sizes

Longer answer: The theme options object shown in the code editor is piped directly into `createMuiTheme()`. Values shown in the Tool Panel are pulled directly from the resulting `Theme` object. Material-UI uses `rem` font sizes by default for typography font sizes, so unless explicitly set, that's the unit used.

The Font Size input in the Tool Panel has a drop down on the units to select different units:

![image](https://user-images.githubusercontent.com/7115788/92001392-a1e8cb00-ed0c-11ea-8711-f4d0241ef3af.png)

Or, if you explicitly set the font size for a typography type in the code editor, it will switch to that unit in the Tool Panel

e.g.

```js
{
  palette: {
    type: 'light',
    primary: {
      main: '#3f51b5',
    },
    secondary: {
      main: '#f50057',
    },
  },
  typography: {
    h1: {
      fontSize: 75,
    },
  },
}
```

**Comment by bareynol** [comment]
On that note, though, I'm not particularly aware of a reason not to use `rem`. It's relative to the font-size of the root `html` element, so with it being used as default, you can change all of the typography element sizes at once. e.g. if you'd like to increase the font-size of all typography elements by, say, 25%, you could change the base typography fontSize from `14px` to `17px`.

```js
{
  palette: {
    type: 'light',
    primary: {
      main: '#3f51b5',
    },
    secondary: {
      main: '#f50057',
    },
  },
  typography: {
    fontSize: 17,
  },
}
```

Do you know of a reason not to be using `rem` units in 2020?

**Comment by jantimon** [comment]
The idea of REM is to provide a better accessibility by allowing the user to increase the base font size.

Actually that's a great idea and therefore was used a lot especially before all browser vendors provided a good zoom feature.

The problem with consistency - when using REM for parts of the page you need to use it everywhere (media queries, paddings, margins, animations, ...) or your page you will most likely break if the user changes their base font size.

I guess with your dropdown it's good enough - it let's the developer decide if they really want to use REM 👍

**Comment by bareynol** [comment]
After playing around with some of my apps and my browser font size settings, I can definitely see what you mean about spacing issues, and some areas breaking. Thanks for bringing that up, it's a good reminder to ensure accessibility needs are being supported.

Based on the [Material-UI docs on Font Size](https://material-ui.com/customization/typography/#font-size), rem units appear to be an intentional choice, citing accessibility support as a reason. I always understood that and the [MDN note on font-size](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size#Pixels) to mean that using `rem`/`em` is strongly encouraged in the case that the user changes their base font size, so I'm a bit surprised to hear this opinion.

I must admit though, I'm not up-to-date on what methods the visually-impaired use to navigate the web, so purely as a learning opportunity for me, if you have any links to info about that, and guidelines for developing for that, I'd be very interested in reading it!

In any case, I think the best stance is to keep the theme editor unopinionated about it, and default the decision to Material-UI.

I definitely agree though, best not to force that opinion on developers, and have a dropdown to change it.
